ALTER TABLE posts ALTER COLUMN body SET NOT NULL;
ALTER TABLE posts ALTER COLUMN title SET NOT NULL;
ALTER TABLE posts DROP CONSTRAINT posts_check;
ALTER TABLE posts DROP CONSTRAINT posts_title_check;